#!/bin/bash

if [ -e lock ];
then
	echo "update locked; quitting" >&2;
	exit 1;
fi

touch lock;

COURSE_URL="http://www.groupes.polymtl.ca/public/Horaire/horsage.csv"
CLOSED_URL="http://www.groupes.polymtl.ca/public/Horaire/fermes.csv"
WGETFAIL=0  # false

wget -O "courses.csv.new" $COURSE_URL 2> /dev/null || WGETFAIL=1;
if [ $WGETFAIL -eq 0 ];
then
	wget -O "closed.csv.new" $CLOSED_URL 2> /dev/null || WGETFAIL=1;
fi

if [ $WGETFAIL -eq 1 ];
then
	echo "wget failed" >&2;
	rm lock;
	exit 1;
fi

if [ ! -s courses.csv.new ];
then
	echo "new courses.csv is empty";
	rm lock;
	exit 1;
fi

rm -f courses.csv closed.csv
mv courses.csv.new courses.csv
mv closed.csv.new closed.csv

chmod 644 "courses.csv"
chmod 644 "closed.csv"

rm -f lock

