#!/bin/bash

if [ -e lock ];
then
	echo "update locked; quitting" > /dev/stderr;
	exit 1;
fi

touch lock;

# if you are located outside of the polymtl.ca network but have access to a unix machine inside you can tunnel the connection through ssh (port 6789 is just random)(this is usually an interactive command, you'll have to type your password, look into public keys and ssh agent if you want to automate it)
# if you want to do this, uncomment the next two lines and comment the one below (starting with smbclient //ecole.polymtl.ca/public)
#ssh -L 6789:ecole.polymtl.ca:139 user@host.polymtl.ca
#smbclient //127.0.0.1/public -p 6789 -N -c 'cd horaire; get horsage.csv courses.csv.new; get fermes.csv closed.csv.new'
# if you don't have access to a unix machine at polymtl.ca but are a student there you can register for an account on the STEP (http://step.polymtl.ca). Alternatively, you can try using the VPN.

smbclient //ecole.polymtl.ca/public -N -c 'cd horaire; get horsage.csv courses.csv.new; get fermes.csv closed.csv.new'

if [ ! -s courses.csv.new ];
then
	echo "new courses.csv is empty";
	rm lock;
	exit 1;
fi

rm -f courses.csv closed.csv
mv courses.csv.new courses.csv
mv closed.csv.new closed.csv

chmod 644 "courses.csv"
chmod 644 "closed.csv"

rm -f lock

